version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: "1.20.1"
    ports:
      - "25565:25565"
    volumes:
      - fabric:/data

volumes:
  fabric: {}