version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: "1.20.1"
    ports:
      - "25565:25565"
    volumes:
      - fabric:/data
      - ./build/libs/cross-0.1.0.jar:/data/mods/cross-0.1.0.jar
      - ./api/fabric-api-0.91.1+1.20.1.jar:/data/mods/fabric-api-0.91.1+1.20.1.jar

volumes:
  fabric: {}